Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: app.delete_table
      CodeUri: /Users/elvisngwesse/Desktop/AWS_Repos/7-Databases-AWS/dynamo-db/.aws-sam/build/UpdateEmployee
      Runtime: python3.9
      Architectures:
        - x86_64